// passwordmanager/src/components/Login.tsx
import {IonButton, IonInput, IonTitle, IonCardContent, IonCardHeader, IonCard, IonItem, IonLabel} from "@ionic/react";
import './Login.css';
import React from 'react';


const Dash = require('dash');

//For passing props
interface ILoginProps{
    callback(client: Object): any,
}

export class Login extends React.Component<ILoginProps>{
    //Variables
    mnemonic: string;
    clientOpts: {
        network: string,
        wallet: {
            mnemonic: string
        },
        apps: Object
    };

    //Constructor
    constructor(props:any) {
        super(props);

        this.mnemonic = "";

        this.clientOpts = {
            network: 'testnet',
            wallet: {
                mnemonic: "",
            },
            apps: {
            }
        }

        this.state = {show: false};

        //Binding functions to this component
        this.login = this.login.bind(this);
        this.mnemonicChanged = this.mnemonicChanged.bind(this);
    }

    //Functions
    login(){
        const client = new Dash.Client(this.clientOpts);
        console.log("Logged in. Mnemonic is valid.")
        console.log(client);

        this.props.callback(this.mnemonic);
    }

    mnemonicChanged(event: any){
        this.clientOpts["wallet"].mnemonic = event.detail.value;
    }

    render(){
        return (
            (<div>
                <IonCard>
                    <IonCardHeader>
                        <IonTitle>
                            Login
                        </IonTitle>
                    </IonCardHeader>
                    <IonCardContent>
                        <IonItem>
                            <IonLabel position="floating">Enter Mnemonic</IonLabel>
                            <IonInput onIonChange={this.mnemonicChanged}/>
                        </IonItem>
                        <IonButton onClick={this.login}>
                            Login
                        </IonButton>
                    </IonCardContent>
                </IonCard>
            </div> )
        );
    }
}



export default Login;

// passwordmanager/src/views/Login.vue
<template>
  <ion-card>
    <ion-card-header>
      <ion-card-title>Login</ion-card-title>
    </ion-card-header>

    <ion-card-content>
      <ion-item>
        <ion-label position="floating">Enter Mnemonic</ion-label>
        <ion-input v-model="this.clientOpts.wallet.mnemonic"></ion-input>
      </ion-item>
      <ion-button color="primary" @click="this.login()">Login</ion-button>
    </ion-card-content>

  </ion-card>


</template>

<script>
import { IonCard, IonCardContent, IonCardTitle, IonLabel, IonInput, IonItem, IonButton , IonCardHeader  } from '@ionic/vue';

export default({
  components: { IonCard, IonCardContent, IonCardTitle, IonInput, IonItem, IonLabel, IonButton, IonCardHeader },
  data() {
    return {
      clientOpts: {
        network: 'testnet',
        wallet: {
          mnemonic: "",
        },
      }
    }
  },
  methods:{
    login(){
      const mnemonic = this.clientOpts.wallet.mnemonic;
      this.$router.push({ name: 'passwords', params: { mnemonic: mnemonic }});
    },
  },

});
</script>
